cloud: workspaces-cloud # You may specify `cloud_id` instead
max_workers: 10
head_node_type:
  name: head_node_type
  instance_type: m6i.2xlarge
worker_node_types:
  - name: cpu_worker
    instance_type: c6i.4xlarge
    min_workers: 0
    max_workers: 10
    use_spot: false
  - name: gpu_worker
    instance_type: g5.4xlarge
    min_workers: 5
    max_workers: 10
    use_spot: false
aws:
  BlockDeviceMappings:
  - DeviceName: "/dev/sda1"
    Ebs:
      VolumeSize: 300
      VolumeType: "gp3"
      DeleteOnTermination: true
      Iops: 5000
      Throughput: 1000

# To create this compute config, make sure that you have the anyscale cli installed via:
# `pip install anyscale`
# If you are running this from a local environment, you also need to have your Anyscale credentials.
# You can find more information about Anyscale credentials by clicking on your name in Anyscale and
# then clicking on Credentials.

# To create a compute config, you can use the following:
# `anyscale cluster-compute create training_compute_config.yml --name anyscale-xgboost-gpu-job`