base_image: anyscale/ray:2.1.0-py39
env_vars:
  CUSTOM_EFS_IP: '10.0.12.131'
python:
  pip_packages:
    - datasets==2.7.1
    - huggingface-hub==0.11.1
    - ipywidgets==8.0.2
    - scikit-learn==1.1.3
    - torch==1.13.0
    - torchvision==0.14.0
    - transformers==4.24.0
    - colorama==0.4.4
    - tensorboardX
    - xgboost
    - xgboost-ray
post_build_cmds:
  - /home/ray/anaconda3/bin/python -m pip uninstall -y modin
  - mkdir ../anyscale-training
  - git clone --branch training-session https://github.com/ray-project/ray-educational-materials ../anyscale-training/.


# To create this cluster environment, make sure that you have the anyscale cli installed via:
# `pip install anyscale`
# If you are running this from a local environment, you also need to have your Anyscale credentials.
# You can find more information about Anyscale credentials by clicking on your name in Anyscale and
# then clicking on Credentials.
#
# The command to create the cluster environment is (name needs to be unique):
# `anyscale cluster-env build training_cluster_env.yml --name anyscale-training-cluster-environment`